config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # index
  root to: "islands#index"

  resources :islands do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :dashboard, only: :index

end

#   get "/islands", to: 'islands#index'

#   get '/islands/new', to: 'islands#new'
#   post '/islands', to: 'islands#create'
#  # show
#  get '/islands/:id', to: 'islands#show', as: :island
#  #edit
#   get '/islands/:id/edit', to: 'islands#edit'
#  #update
#  patch '/islands/:id', to: 'islands#update'
#  #destroy
#  delete '/islands/:id', to: 'islands#destroy'
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :island
end

app/models/island.rb
class Island < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :islands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:destroy, :show]
  before_action :set_island, only: [:new, :create]

  # def new
  #   @booking = Booking.new
  # end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.island = @island
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
      #redirect to dashboard page
    else
      render "islands/show"
    end
  end

  def destroy
    @booking.destroy
    redirect_to island_path(@booking.island)
  end

  private

  def booking_params
    params.require(:booking).permit(:description, :start_time, :end_time, :user_id, :island_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_island
    @island = Island.find(params[:island_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user)
  end
end

app/controllers/islands_controller.rb
class IslandsController < ApplicationController
  before_action :set_island, only: [:show]
  before_action :set_user, only: [:create]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @islands = Island.where(sql_query, query: "%#{params[:query]}%")
    else
      @islands = Island.all
    end

    @markers = @islands.geocoded.map do |island|
      {
        lat: island.latitude,
        lng: island.longitude
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @island = Island.new
  end

  def create
    @island = Island.new(island_params)
    @island.user_id = @user.id
    if @island.save
      redirect_to island_path(@island)
    else
      render :new
    end
  end

  def edit
  end

  def update
    redirect_to island_path(@island)
  end

  def destroy
    @island.destroy
    redirect_to island_path
  end

private

  def island_params
    params.require(:island).permit(:name, :address, :description, :daily_rate, :availability)
  end

  def set_island
    @island = Island.find(params[:id])
  end

  def set_user
    @user = current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @islands = Island.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="container">
  <div id="confirmation" class="card" style="width: 20rem;">
    <div class="card-body">
      <h5 class="card-title">Congrats, your island awaits you!</h5>
      <h6 class="card-subtitle mb-2 text-muted">Address: <%= @booking.island.address %></h6>
      <p class="card-text">Description: <%= @booking.description %><br>From: <%= @booking.start_time %> To: <%= @booking.end_time %>
      </p>
      <%= link_to "To my bookings", dashboard_index_path %>

    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="card-booking">
  <% @bookings.each do |booking| %>
    <div class="card-product">
    <img src="https://source.unsplash.com/featured/?islands,beach" />
      <div class="card-product-infos">
        <h2><%#= booking.description %> <%= booking.description %> </h2>
        <h3><%#= booking.description %> <%= booking.island.name %> </h2>
        <p><%#= booking.date %><strong>relevant info</strong> From: <%= booking.start_time %> To: <%= booking.end_time %> </p>
        <p><%#= booking.date %><strong>This is an island for savvy people, mind your own business</strong> </p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Back to all Islands", root_path %>

app/views/islands/_form.html.erb
<%= form_for(island) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :daily_rate %>
  <%= f.number_field :daily_rate %>
  <%= f.submit %>
<% end %>

app/views/islands/edit.html.erb
<%= form_for @island do |f| %>
<%= f.label :name %>
<%= f.string :name %>
<%= f.label :address %>
<%= f.string :address %>
<%= f.label :description %>
<%= f.string :description %>
<%= f.label :daily_rate %>
<%= f.integer :daily_rate %>

<% end %>

app/views/islands/index.html.erb
<%= render "components/banner" %>
<%= render "components/cards" %>

app/views/islands/new.html.erb
<h1>Add a island</h1>

<%= render "form", island: @island %>

app/views/islands/show.html.erb
<div class="container">

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner carousel-height"  style="height: 400px; margin-top: 100px;">
      <div class="carousel-item active">
        <img class="d-block w-100" src="https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="Second slide" style="height: 500px;">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://images.unsplash.com/photo-1602749035334-54ebc4010e0c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80" alt="First slide" style="height: 700px;">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://images.unsplash.com/photo-1577372970039-2ac351969c87?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2550&q=80" alt="Third slide" style="height: 500px;">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


<div class="island-details" >
  <div class="card-trip mr-4" >
    <div class="card-body card-trip-info">
      <h2 class="card-title" id="header"><%= @island.name %></h2>
      <h2 class="card-subtitle mb-2 text-muted"><%= @island.address %></h2>
      <p class="card-text"></p>
      <h2 class="card-text"><%= @island.daily_rate %>€</h2>
      <!-- <p class="card-text"><%= @island.availability %></p> -->
    </div>
  </div>

  <div class="description">
    <p><%= @island.description %></p>
  </div>
</div>

  <div id="map"
   style="width: 100%; height: 600px;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

    <div class="all-cards">
      <div class="card-trip">
        <div class="card-trip-infos">
          <div id="header"><h3>Book your dream Island <%= @island.name %></h3></div>
            <%= simple_form_for [@island, @booking] do |f| %>
            <%= f.input :description, placeholder: 'Enter relevant info about your booking' %>
            <%= f.input :start_time, placeholder: 'Enter a date' %>
            <%= f.input :end_time, placeholder: 'Enter a date' %>
            <%= f.submit class: 'btn btn-flat' %>
          <% end %>
        </div>
      </div>
    </div>



<a class="btn btn-flat" href="/">Back to all Islands</a>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HolySkinGoesIsland</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

   <body>
      <%= render "components/navbar" %>
       <div class="content-wrapper">
        <%= yield %>
        </div>
      <%= render "components/footer" %>
  </body>
</html>